name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  xcode_select:
    strategy:
      matrix:
        os: ["macos-10.15", "macos-11.0"]
    runs-on: ${{ matrix.os }}

    steps:
      - run: |
          xcode-select
