name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  xcode_select:
    strategy:
      matrix:
        os: [macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
      - run: |
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.3.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.2.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.1.1.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.1.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.7.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.6.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.5.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.4.1.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.3.1.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_11.2.1.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_10.3.app'
          xcode-select --print-path
          clang++ -v

      - run: |
          sudo xcode-select --switch '/Applications/Xcode_12.4.app'
          xcode-select --print-path
          clang++ -v
