name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  xcode_select:
    strategy:
      matrix:
        macos_version: ["10.15", "11.0"]
    runs-on: 'macos-${{ matrix.macos_version }}'

    steps:
      - run: |
          xcode-select
